
global:
    r: 1e-2
    nside: 2048
    Lmax: 3050
    coord_out: 'G'
    output_path: '/pscratch/sd/i/iabril/data/newr/act/240112/'

  
delens:
    alpha_phi: 0.
    alpha_psi: 0.7

ell:
    lmax_out: 1000
    lmin_out: 0
    dell_out: 20

    lmax_phi: 3000
    lmin_phi: 600 #300

    lmax_psi: 200
    lmin_psi: 30

reconstruction:
    psi: 'BB'
    phi: 'TT'

cmb:
    seed: 0

foreground:
    mask:
        footprint: 'planck_97' # 'planck_20'
        # footprint_path: '/global/cfs/cdirs/act/data/iabril/SO/mask_apodized_david_nside512.fits' # '/pscratch/sd/i/iabril/data/PlanckData/HFI_Mask_GalPlane-apo5_2048_R2.00.fits'
        # coord: 'C' # 'so': 'C', 'planck': G
        # apo_deg: 5.0
    dust:
        # {'van': [90], 'pysm_d1': [all], 'DF': [95]}
        type: 'planck' # 'van' 'pysm_d1' 'DF' 
        # coord: 'G'
        freq: 90 # '150'
        path: '/pscratch/sd/i/iabril/data/' 
